<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="HWYRSQ2" failures="0" tests="4" name="Claims_Contact_Assist_RunTest 1" time="12.7" errors="0" timestamp="21 Nov 2018 18:54:27 GMT">
  <testcase classname="Automation.Claims.Claims_Contact_Assist_RunTest" name="@AfterTest EndBatch" time="0.057">
    <failure type="java.lang.IllegalStateException" message="No reporters were started. Atleast 1 reporter must be started to flush results.">
      <![CDATA[java.lang.IllegalStateException: No reporters were started. Atleast 1 reporter must be started to flush results.at com.aventstack.extentreports.Report.flush(Report.java:182)at com.aventstack.extentreports.ExtentReports.flush(ExtentReports.java:281)at Automation.Claims.Claims_Contact_Assist_RunTest.EndBatch(Claims_Contact_Assist_RunTest.java:141)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.base/java.lang.reflect.Method.invoke(Method.java:564)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:451)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)at org.testng.TestRunner.afterRun(TestRunner.java:725)at org.testng.TestRunner.run(TestRunner.java:509)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- @AfterTest EndBatch -->
  <testcase classname="Automation.Claims.Claims_Contact_Assist_RunTest" name="RunClaims_Contact_Assis2" time="0.0">
    <skipped/>
  </testcase> <!-- RunClaims_Contact_Assis2 -->
  <testcase classname="Automation.Claims.Claims_Contact_Assist_RunTest" name="RunClaims_Contact_Assis2" time="0.0">
    <skipped/>
  </testcase> <!-- RunClaims_Contact_Assis2 -->
  <testcase classname="Automation.Claims.Claims_Contact_Assist_RunTest" name="RunClaims_Contact_Assist1" time="0.0">
    <skipped/>
  </testcase> <!-- RunClaims_Contact_Assist1 -->
  <testcase classname="Automation.Claims.Claims_Contact_Assist_RunTest" name="RunClaims_Contact_Assist1" time="0.0">
    <skipped/>
  </testcase> <!-- RunClaims_Contact_Assist1 -->
</testsuite> <!-- Claims_Contact_Assist_RunTest 1 -->
